# Generated by Django 3.0.4 on 2020-05-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0003_produit_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
