# Generated by Django 3.0.4 on 2020-07-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0006_auto_20200713_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bill.Category'),
        ),
    ]
